### ISSUE TITLE
 Is gnss data necessary for retrieval？

### ISSUE THREAD

**Issue by FUNDREAM99** [jac99/MinkLoc3Dv2#1]
I have read your paper and run the code you provide on the Github. It is  a great work.

I would like to use MinkLoc3Dv2 for point cloud retrieval by using the global descriptor. in the work of figure 3. You used the query point clouds to retrieve the corresponding point clouds.

I would like to know Is gnss data necessary for this process?

**Comment by jac99** [comment]
Hi,
GNSS (or GPS) data is used to generate the training set. For each query point cloud, we find positive/similar point clouds (that are not more than 10 meters away) and negative/dissimilar point clouds (that are at least 50 meters away).
For retrieval itself, we push the 3D point cloud through the trained network and compute its descriptor (a 256-dimensional real-valued vector). Then, we find the point cloud in the database with the most similar descriptor. 
However, we need to have a position of the most similar point cloud in the database, to reason about the location of the query point cloud. This can come from GSNN/GPS, or we can possibly use a global map by merging all database point clouds using some point cloud-based SLAM method.

**Comment by FUNDREAM99** [comment]
Thank you for your prompt reply,It's very helpful to me.
