### ISSUE TITLE
Sensor recommendation

### ISSUE THREAD

**Issue by oym1994** [jac99/MinkLoc3Dv2#2]
Hi, thanks for your great job!
I am gonna to test your work in our project. We have done some investigation before. In some lidar-based place recognition method, lidar with 360 degree data with at least 36 lines is recommended. How about the adaptability to different lidar sensor of your method? 
Thank your for your attention and keep waiting for kind response!

**Comment by jac99** [comment]
Hi, so far I have tested our method on 360 degree LiDAR with 64 channels (Mulran dataset and Apollo SouthBay dataset). Point clouds in these datasets span a larger area and have more points than point clouds used by the original method. So some changes in the network architecture and point cloud quantization steps (voxel size) were needed. You can easily do these changes, by amending the model configuration file in: `models/minkloc3dv2.txt` file.
`channels` control the number of convolutional blocks in the network and the number of channels in each block (refer to the diagram of the network in my paper). For larger point clouds it would be reasonable to make the network deeper and add more channels. 
For 360-degree point clouds, I would recommend changing coordinates to polar and change quantization steps. E.g.:
```
coordinates = polar
# Quantization steps for sectors (in degrees), rings (in meters) and z coordinate (in meters)
quantization_step = 1., 0.3, 0.2
```
You need to experiment for yourself to choose the best parameters.

**Comment by jac99** [comment]
Also, make sure you add random rotation around Z axis to training data augmentation if you'd like to have rotation-invariant descriptor. Using only polar coordinates, without adding random rotations, likely will not produce a rotationally-invariant descriptor.

**Comment by oym1994** [comment]
Got it！ Thanks for your kind response.

**Comment by oym1994** [comment]
I have tried it on my own dataset with a 16 bin lidar. it performs very well and shows that the pretrained model has a great generalization ability. 

Another problem comes. Have you tried to deploy the model to c++ project? I tried to convert the model to the libtorch .pt model, but some error occured as below:
converting code:
`
 traced_script_module = torch.jit.trace(model, batch)
 traced_script_module.save("MinkLoc3Dv2.pt")
`
errors:
`
File "/home/hw-robot/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 741, in trace
    return trace_module(
  File "/home/hw-robot/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 983, in trace_module
    _check_trace(
  File "/home/hw-robot/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/hw-robot/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 516, in _check_trace
    traced_outs = run_mod_and_filter_tensor_outputs(traced_func, inputs, "trace")
  File "/home/hw-robot/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 449, in run_mod_and_filter_tensor_outputs
    raise TracingCheckError(
torch.jit._trace.TracingCheckError: Tracing failed sanity checks!
encountered an exception while running the trace with test inputs.
Exception:
	The following operation failed in the TorchScript interpreter.
	Traceback of TorchScript (most recent call last):
	/home/hw-robot/.local/lib/python3.8/site-packages/MinkowskiEngine/MinkowskiSparseTensor.py(329): initialize_coordinates
	/home/hw-robot/.local/lib/python3.8/site-packages/MinkowskiEngine/MinkowskiSparseTensor.py(271): __init__
	/home/hw-robot/relocalization/MinkLoc3Dv2/models/minkloc.py(23): forward
	/home/hw-robot/.local/lib/python3.8/site-packages/torch/nn/modules/module.py(1090): _slow_forward
	/home/hw-robot/.local/lib/python3.8/site-packages/torch/nn/modules/module.py(1102): _call_impl
	/home/hw-robot/.local/lib/python3.8/site-packages/torch/jit/_trace.py(958): trace_module
	/home/hw-robot/.local/lib/python3.8/site-packages/torch/jit/_trace.py(741): trace
`

Do you have any suggestion about this error?
Thank you again!

**Comment by jac99** [comment]
Hi, thanks for info. It's great to hear that the model performs well using other datasets.
Unfortunately, I cannot help you with c++ migration task. I'm not sure if this will be even possible. As MinkowskiEngine library has it's own low-level cuda kernels. And migration using torch script or exporting models to ONNX likely will not work. Try to search issues log of MinkowskiEngine library. Maybe there'll be some clue there.

**Comment by oym1994** [comment]
Thanks for your kind response! We will try your advice.
