### ISSUE TITLE
MemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by fentuoli** [jac99/MinkLoc3Dv2#3]
Dear Author,
     I'm sorry to bother you, I have met this problem when I ran to 35 epoches:
_" File "~/venv38/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 72, in forward
    return fw_fn(
MemoryError: std::bad_alloc: cudaErrorMemoryAllocation: out of memory"_
       The version of MinkowskiEngine is 0.5.4, but the version of cuda is 11.6, I wonder to know if this problem is caused by the version of cuda, I couldn't change the version of cuda casully for it may cause trouble to other users. 
       I'm looking forward to your reply!
Best Wishes!

**Comment by fentuoli** [comment]
And could you tell me what is your GPU version？ I use NVIDIA GeForce RTX 3090 which only supports cuda version above 11.0, but  if I change to use NVIDIA GTX 1060, the memory is not enough. Do I need a GPU with more than 20G memory and supports cuda 10.2 to train？

**Comment by jac99** [comment]
Hi, I've run the model on RTX2080Ti with CUDA 10.2. I think MinkowskiEngine library (library used in my work for sparse 3D convolutions) should work with higher version of CUDA.
I've seen, that recently they posted an update on MinkowskiEngine website, to support PyTorch 1.11 and CUDA 11.6. So maybe try these versions. See MinkowskiEngine website for more info.

You should be able to train on GPU with less than 20GB of RAM. I've trained the model on RTX2080Ti. You can decrease the value of batch_split_size parameter in the config file. Current value is 128 and you can try to decrease it to 64. This should decrease the GPU memory usage.

**Comment by fentuoli** [comment]
> Hi, I've run the model on RTX2080Ti with CUDA 10.2. I think MinkowskiEngine library (library used in my work for sparse 3D convolutions) should work with higher version of CUDA. I've seen, that recently they posted an update on MinkowskiEngine website, to support PyTorch 1.11 and CUDA 11.6. So maybe try these versions. See MinkowskiEngine website for more info.
> 
> You should be able to train on GPU with less than 20GB of RAM. I've trained the model on RTX2080Ti. You can decrease the value of batch_split_size parameter in the config file. Current value is 128 and you can try to decrease it to 64. This should decrease the GPU memory usage.

Thanks for your reply, I will have a try. Thanks a lot again!

**Comment by jac99** [comment]
Closed due to inavtivity
