### ISSUE TITLE
how about the pointcloud generated by depth image?

### ISSUE THREAD

**Issue by frischzenger** [jac99/MinkLoc3Dv2#6]
how about the pointcloud generated by depth image? such as real sense, kinect .... ?
thanks

**Comment by jac99** [comment]
You can give it a try. 
The MinkLoc3D architecture was optimized for rather small point clouds from a variant of Oxford RobotCar dataset proposed in PointNetVLAD paper. Point coordinates are normalized to -1..1 range and point clouds are downsampled to 4096 points.
But it should work with larger point clouds. You only need to fine tune model parameters in models/minkloc3dv2.txt file:
- Change quantization_step. Current quantization_step is 0.01, which is fine when points have coords in -1..1 range (this gives app. 200 quantize coords in each direction). Choose quantization step, so you have no more than 400 quantized coords in one dimension.
- Try different network configurations (e.g. more layers) - this is controlled by planes parameters. planes=64,128,64,32 means that we have 4 convolutional blocks, outputting feature maps with respectively 64, 128, 64 and 32 channels. You can change the number of channels and add additional blocks. Only make sure that number of ones in layers (currently layers=1,1,1,1) is the same as a number of entries in planes parameters.
- num_top_down=2 controls the number of top down blocks (see network diagram in the paper)
-
I don't know whether using MinkLoc3Dv2 for pointclouds generated by depth images will give better results than using 2D CNN operating on raw depth maps. But you can give it a try.

**Comment by frischzenger** [comment]
Thank you for the response，i'll have a try
