### ISSUE TITLE
Are you serious about cuda 10.2 on ubuntu 20.04?

### ISSUE THREAD

**Issue by JzHuai0108** [jac99/MinkLoc3Dv2#8]
Dear Sir,

I am on ubuntu 20. As your readme recommend cuda 10.2. I tried to install it.
However, the available cuda from apt-cache is cuda 11.x as shown [here](https://linux.how2shout.com/how-to-install-cuda-on-ubuntu-20-04-lts-linux/).
Also, I see that people are advising not to use [cuda 10.2 on ubuntu 20.04](https://ww2.mathworks.cn/matlabcentral/answers/687133-how-to-install-supported-cuda-toolkit-10-2-on-ubuntu-20-04-lts-linux).
Since the repo is two years old, do you still recommend using cuda 10.2 on ubuntu 20?

If this is the case, I may proceed with the guide [here](https://datacrunch-io.medium.com/installing-cuda-on-your-datacrunch-io-server-8bbc1cf571ee). Do you think this guide is viable?

**Comment by jac99** [comment]
Hi, 
I'm not working on this project anymore and I don't know if it'll work with the newer CUDA version. 
MinkLoc3Dv2 is dependent on MinkowskiEngine library (https://github.com/NVIDIA/MinkowskiEngine). Try to install MinkowskiEngine library with some later CUDA version (I've heard it doesn't work with CUDA 12, but maybe it works with some CUDA 11.x version). If MinkowskiEngine works with CUDA 11.x, MinkLoc3D should work as well.

Alternatively use a Docker to run CUDA 10.2 with previous PyTorch version in a docker image.

**Comment by jac99** [comment]
MinkowskiEngine lib (https://github.com/NVIDIA/MinkowskiEngine/tree/master) has a Docker installation. 
It should be possible to run MinkLoc3Dv2 using this docker image.

**Comment by JzHuai0108** [comment]
Thank you, Sir. 
I am browsing point cloud place recognition papers, trying to identify a good candidate for my problem at hand, place recognition with a 4d radar of sparse point clouds.
I will figure it out soon.
